version: '3'

# django - postgres

services: 
    django-service:
        image: python:3.8-alpine
        container_name: django
        build: .
        command: python3.8 manage.py runserver 0.0.0.0:80
        ports:
            - 80:80
        env_file:
            - ./.env.prod
        volumes: 
            - ./:/usr/src/app/
        depends_on: 
            - db-service
    #postgres service
    db-service:
        image: postgres:13.3-alpine
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=example_project
            - POSTGRES_PASSWORD=example_project
            - POSTGRES_DB=example_project
        networks: 
            - local-bridge
networks: 
    local-bridge:
        driver: bridge
volumes:
    postgres_data: